---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connection-handler
data:
  application-kubernetes.yaml: |-
    spring:

      cloud:
        stream:
          kafka:
            binder:
              brokers: kafka:9092

      redis:
        host: redis-1601316548-master

      zipkin:
        enabled: true
        base-url: http://zipkin-server:9411/

    logging.level:
      org.springframework.data.redis: INFO
      org.springframework.integration.redis: INFO
      org.springframework.web: INFO

    server:
      port: 8080

    tcp-server:
      url: 192.168.86.78
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: connection-handler
  name: connection-handler
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: connection-handler
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: connection-handler
  name: connection-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connection-handler
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: connection-handler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - image: dmfrey/connection-handler:latest
          name: connection-handler
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          env:

            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes

            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis-1601316548

          resources: {}
status: {}
