---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zipkin-server
  name: zipkin-server
spec:
  ports:
    - name: 9411-9411
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    run: zipkin
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: zipkin
  name: zipkin
spec:
  containers:
    - image: openzipkin/zipkin
      name: zipkin
      ports:
        - containerPort: 9411
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
