
logging.level:
  org.apache.kafka: WARN
  org.springframework.cloud.stream: WARN
  org.springframework.cloud.function: WARN
  org.springframework.data.redis: INFO
  org.springframework.integration.handler: WARN
  org.springframework.integration.ip: WARN
  org.springframework.integration.redis: INFO
  org.springframework.integration.support.leader: INFO
  org.springframework.integration.support.locks: INFO
  org.springframework.web: DEBUG
  com.vmware.dmfrey.dataflow: DEBUG

server:
  port: ${PORT:9091}

client:
  id: 14f47426-d6f5-4cd9-99e7-af2f47dffe54

tcp-server:
  url: localhost
  port: 6666

spring:

  cloud:

    stream:
      bindings:
        adapter-out-0:
          destination: adapter.raw

      source: adapter

  sleuth:
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

  zipkin:
    enabled: false

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

---
spring:
  profiles: kubernetes
