
logging.level:
  org.springframework.cloud.stream: INFO
  org.springframework.integration.ip: INFO
  org.springframework.web: DEBUG
  com.vmware.dmfrey.dataflow: DEBUG

server:
  port: 9090

client:
  id: 14f47426-d6f5-4cd9-99e7-af2f47dffe54

tcp-server:
  url: localhost
  port: 6666
  poolSize: 5

spring:

  cloud:

    stream:
      bindings:
        adapter-out-0:
          destination: adapter.raw

      source: adapter
